export type GlossaryLink = {
  label: string;
  href: string;
};

export type GlossaryFaq = {
  question: string;
  answer: string;
};

export type GlossaryItem = {
  slug: string;
  term: string;
  name: string;
  seoTitle: string;
  seoDescription: string;
  explanation: string;
  formula: string;
  example: string;
  interpretation: string;
  attention: string;
  relatedMetrics: string[];
  rankingLinks: GlossaryLink[];
  assetLinks: GlossaryLink[];
  faq: GlossaryFaq[];
};

const defaultAssetLinks: GlossaryLink[] = [
  { label: "PETR4", href: "/acoes/petr4" },
  { label: "VALE3", href: "/acoes/vale3" },
  { label: "ITUB4", href: "/acoes/itub4" },
  { label: "MXRF11", href: "/fiis/mxrf11" },
  { label: "XPML11", href: "/fiis/xpml11" },
];

const dividendRankingLinks: GlossaryLink[] = [
  { label: "Ações com maior Dividend Yield", href: "/rankings/maiores-dividend-yield" },
  { label: "FIIs com maior Dividend Yield", href: "/rankings/fiis-maior-dividend-yield" },
];

export const glossaryItems: GlossaryItem[] = [
  {
    slug: "pl",
    term: "P/L",
    name: "Preço sobre Lucro",
    seoTitle: "O que é P/L? Entenda o Preço sobre Lucro",
    seoDescription: "Entenda o indicador P/L, como calcular, como interpretar e quais cuidados tomar ao comparar ações.",
    explanation: "O P/L mostra quantas vezes o mercado está pagando pelo lucro anual da empresa. Ele ajuda a comparar preço e lucro, mas precisa ser visto junto com crescimento, qualidade do lucro e setor.",
    formula: "P/L = Preço da ação ÷ Lucro por ação (LPA)",
    example: "Se uma ação custa R$ 20 e o lucro por ação é R$ 2, o P/L é 10. Isso significa que o preço equivale a 10 vezes o lucro por ação.",
    interpretation: "P/L menor pode indicar uma ação mais barata em relação ao lucro, mas também pode refletir risco, lucro temporário ou expectativa ruim para os próximos anos.",
    attention: "Não compare P/L de setores muito diferentes. Bancos, varejo, energia e tecnologia podem negociar com múltiplos naturalmente distintos.",
    relatedMetrics: ["LPA", "ROE", "Margem líquida", "Valor de mercado"],
    rankingLinks: [{ label: "Ações com menor P/L", href: "/rankings/menores-pl" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "P/L baixo é sempre bom?", answer: "Não. P/L baixo pode indicar desconto, mas também pode refletir queda esperada no lucro, risco alto ou evento não recorrente." },
      { question: "P/L negativo significa o quê?", answer: "Geralmente significa que a empresa apresentou prejuízo. Nesses casos, o indicador costuma perder utilidade." },
    ],
  },
  {
    slug: "pvp",
    term: "P/VP",
    name: "Preço sobre Valor Patrimonial",
    seoTitle: "O que é P/VP? Entenda o Preço sobre Valor Patrimonial",
    seoDescription: "Veja o que significa P/VP, como interpretar esse indicador e em quais setores ele costuma ser mais útil.",
    explanation: "O P/VP compara o preço de mercado com o valor patrimonial por ação ou cota. Ele mostra quanto o investidor paga em relação ao patrimônio contábil.",
    formula: "P/VP = Preço da ação ou cota ÷ Valor patrimonial por ação ou cota",
    example: "Se uma cota custa R$ 90 e o valor patrimonial por cota é R$ 100, o P/VP é 0,90.",
    interpretation: "P/VP abaixo de 1 indica preço abaixo do patrimônio contábil. Isso pode ser oportunidade, mas também pode refletir ativos de baixa qualidade, vacância, risco ou patrimônio superestimado.",
    attention: "Em FIIs, P/VP precisa ser lido junto com qualidade dos imóveis, vacância, rendimentos e liquidez. Em ações, costuma ser mais útil em bancos e seguradoras.",
    relatedMetrics: ["VPA", "Valor patrimonial por cota", "Patrimônio líquido", "ROE"],
    rankingLinks: [
      { label: "Ações com menor P/VP", href: "/rankings/menores-pvp" },
      { label: "FIIs com menor P/VP", href: "/rankings/fiis-menor-pvp" },
    ],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "P/VP abaixo de 1 é sempre barato?", answer: "Não. Pode existir desconto por risco real, queda de qualidade, baixa liquidez ou problemas no ativo." },
      { question: "P/VP serve para FIIs?", answer: "Serve, mas deve ser usado com cautela e junto com segmento, patrimônio, rendimentos, vacância e liquidez." },
    ],
  },
  {
    slug: "dividend-yield",
    term: "Dividend Yield",
    name: "Dividend Yield dos últimos 12 meses",
    seoTitle: "O que é Dividend Yield? Entenda o DY 12m",
    seoDescription: "Entenda o Dividend Yield, como calcular o DY dos últimos 12 meses e quais cuidados tomar ao analisar dividendos.",
    explanation: "O Dividend Yield indica quanto uma ação ou FII distribuiu em proventos em relação ao preço atual. É muito usado por quem busca renda, mas pode ser distorcido por eventos extraordinários.",
    formula: "Dividend Yield = Proventos dos últimos 12 meses ÷ Preço atual × 100",
    example: "Se uma ação custa R$ 50 e pagou R$ 5 em proventos nos últimos 12 meses, o Dividend Yield é 10%.",
    interpretation: "DY mais alto pode indicar maior retorno em proventos, mas também pode ser efeito de queda no preço, pagamento extraordinário ou dado não recorrente.",
    attention: "DY muito alto não deve ser tratado como renda garantida. O Mapa do Ativo filtra valores atípicos nos rankings para reduzir risco de leitura enganosa.",
    relatedMetrics: ["Payout", "Provento extraordinário", "Amortização", "Preço", "Fluxo de caixa"],
    rankingLinks: dividendRankingLinks,
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Dividend Yield alto é sempre bom?", answer: "Não. Pode ser causado por queda forte na cotação, evento extraordinário, amortização ou pagamento que não deve se repetir." },
      { question: "Por que alguns sites mostram DY diferente?", answer: "Cada site pode usar data-base, preço, janela de proventos e critérios diferentes para tratar eventos extraordinários." },
    ],
  },
  {
    slug: "roe",
    term: "ROE",
    name: "Retorno sobre Patrimônio Líquido",
    seoTitle: "O que é ROE? Entenda o Retorno sobre Patrimônio Líquido",
    seoDescription: "Saiba o que é ROE, como esse indicador mede a rentabilidade da empresa e quais cuidados considerar.",
    explanation: "O ROE mede quanto lucro a empresa gera em relação ao patrimônio líquido dos acionistas.",
    formula: "ROE = Lucro líquido ÷ Patrimônio líquido × 100",
    example: "ROE de 20% significa que, para cada R$ 100 de patrimônio líquido, a empresa gerou R$ 20 de lucro.",
    interpretation: "ROE alto pode indicar boa rentabilidade, mas deve ser acompanhado de endividamento, margem, recorrência do lucro e qualidade do patrimônio.",
    attention: "ROE muito alto pode vir de patrimônio reduzido ou alavancagem elevada, não necessariamente de eficiência operacional superior.",
    relatedMetrics: ["ROA", "ROIC", "Margem líquida", "Dívida líquida"],
    rankingLinks: [{ label: "Ações com maior ROE", href: "/rankings/maiores-roe" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "ROE alto é suficiente para escolher uma ação?", answer: "Não. ROE precisa ser analisado junto com dívida, lucro recorrente, setor, governança e preço." },
      { question: "ROE negativo significa o quê?", answer: "Normalmente indica prejuízo ou patrimônio líquido negativo, o que exige análise cuidadosa." },
    ],
  },
  {
    slug: "roa",
    term: "ROA",
    name: "Retorno sobre Ativos",
    seoTitle: "O que é ROA? Entenda o Retorno sobre Ativos",
    seoDescription: "Entenda como o ROA mede a eficiência da empresa em gerar lucro a partir dos seus ativos.",
    explanation: "O ROA mostra quanto lucro a empresa gera em relação ao total de ativos. Ele ajuda a medir eficiência no uso da estrutura da companhia.",
    formula: "ROA = Lucro líquido ÷ Ativos totais × 100",
    example: "ROA de 5% significa que, para cada R$ 100 em ativos, a empresa gerou R$ 5 de lucro.",
    interpretation: "ROA maior tende a indicar uso mais eficiente dos ativos, mas padrões variam bastante entre setores intensivos em capital e negócios mais leves.",
    attention: "Compare ROA entre empresas do mesmo setor. Uma utility e uma empresa de software não têm a mesma estrutura de ativos.",
    relatedMetrics: ["ROE", "ROIC", "Ativos totais", "Margem líquida"],
    rankingLinks: [{ label: "Ações com maior ROE", href: "/rankings/maiores-roe" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "ROA é melhor que ROE?", answer: "Não necessariamente. ROA foca os ativos totais, enquanto ROE foca o patrimônio líquido. Eles respondem perguntas diferentes." },
      { question: "ROA baixo é sempre ruim?", answer: "Não. Setores com muitos ativos físicos podem operar com ROA estruturalmente menor." },
    ],
  },
  {
    slug: "roic",
    term: "ROIC",
    name: "Retorno sobre Capital Investido",
    seoTitle: "O que é ROIC? Entenda o Retorno sobre Capital Investido",
    seoDescription: "Veja como o ROIC mede a eficiência da empresa em gerar retorno sobre o capital investido.",
    explanation: "O ROIC mede o retorno gerado sobre o capital total investido na operação, considerando capital próprio e de terceiros.",
    formula: "ROIC = Resultado operacional após impostos ÷ Capital investido × 100",
    example: "ROIC de 15% indica que a empresa gerou R$ 15 de retorno operacional para cada R$ 100 de capital investido.",
    interpretation: "ROIC acima do custo de capital por vários anos costuma indicar criação de valor, desde que os dados sejam recorrentes.",
    attention: "ROIC deve ser comparado com empresas do mesmo setor e com a necessidade de reinvestimento do negócio.",
    relatedMetrics: ["ROE", "ROA", "EV/EBITDA", "Dívida líquida"],
    rankingLinks: [{ label: "Ações com maior ROIC", href: "/rankings/maiores-roic" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "ROIC alto é sinal de qualidade?", answer: "Pode ser, especialmente quando se mantém por vários anos e supera o custo de capital." },
      { question: "ROIC serve para bancos?", answer: "É menos usado para bancos. Para instituições financeiras, ROE e indicadores regulatórios costumam ser mais relevantes." },
    ],
  },
  {
    slug: "margem-liquida",
    term: "Margem Líquida",
    name: "Lucro líquido sobre receita",
    seoTitle: "O que é Margem Líquida? Entenda esse indicador",
    seoDescription: "Entenda como a margem líquida mostra a porcentagem da receita que vira lucro líquido.",
    explanation: "A margem líquida mostra qual porcentagem da receita vira lucro líquido depois de custos, despesas, juros e impostos.",
    formula: "Margem líquida = Lucro líquido ÷ Receita líquida × 100",
    example: "Margem líquida de 12% significa que a cada R$ 100 de receita, R$ 12 viram lucro líquido.",
    interpretation: "Margens maiores podem indicar poder de preço, eficiência ou modelo de negócio mais rentável, mas variam muito por setor.",
    attention: "Margem isolada pode enganar quando há evento não recorrente, ganho financeiro ou mudança contábil relevante.",
    relatedMetrics: ["ROE", "ROA", "Lucro líquido", "Receita"],
    rankingLinks: [{ label: "Ações com maior ROE", href: "/rankings/maiores-roe" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Margem líquida alta é sempre melhor?", answer: "Geralmente é positivo, mas precisa ser sustentável e comparada com empresas semelhantes." },
      { question: "Por que margens variam tanto?", answer: "Setores têm estruturas diferentes de custo, capital, competição e impostos." },
    ],
  },
  {
    slug: "ev-ebitda",
    term: "EV/EBITDA",
    name: "Valor da firma sobre EBITDA",
    seoTitle: "O que é EV/EBITDA? Entenda esse múltiplo",
    seoDescription: "Veja como interpretar EV/EBITDA e por que esse indicador é usado para comparar empresas.",
    explanation: "O EV/EBITDA compara o valor total da firma, incluindo dívida líquida, com a geração operacional aproximada de caixa medida pelo EBITDA.",
    formula: "EV/EBITDA = Valor da firma ÷ EBITDA",
    example: "EV/EBITDA de 8 significa que o valor da firma equivale a 8 vezes seu EBITDA anual.",
    interpretation: "Múltiplos menores podem indicar preço mais baixo em relação à geração operacional, mas precisam ser avaliados com crescimento, risco e dívida.",
    attention: "EV/EBITDA não substitui análise de lucro líquido, fluxo de caixa, CAPEX e estrutura de capital.",
    relatedMetrics: ["Dívida líquida", "EBITDA", "Valor de mercado", "Dívida líquida/EBITDA"],
    rankingLinks: [{ label: "Ações com maior valor de mercado", href: "/rankings/maiores-valor-de-mercado" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "EV/EBITDA menor é sempre melhor?", answer: "Não. Pode indicar desconto, mas também risco, baixa qualidade ou piora esperada do negócio." },
      { question: "Por que usar valor da firma?", answer: "Porque ele considera tanto o valor de mercado quanto a dívida líquida da companhia." },
    ],
  },
  {
    slug: "divida-liquida-ebitda",
    term: "Dív.Líq/EBITDA",
    name: "Dívida líquida sobre EBITDA",
    seoTitle: "O que é Dívida Líquida/EBITDA?",
    seoDescription: "Entenda como a Dívida Líquida/EBITDA ajuda a avaliar o endividamento de uma empresa.",
    explanation: "A Dívida Líquida/EBITDA indica quantos anos de EBITDA seriam necessários para pagar a dívida líquida, em uma leitura simplificada.",
    formula: "Dívida líquida/EBITDA = Dívida líquida ÷ EBITDA",
    example: "Dív.Líq/EBITDA de 2 indica que a dívida líquida equivale a aproximadamente 2 anos de EBITDA.",
    interpretation: "Quanto maior o indicador, maior tende a ser o risco financeiro, mas o nível aceitável depende do setor e da previsibilidade de caixa.",
    attention: "Empresas de infraestrutura podem suportar dívida maior que varejistas cíclicas, por exemplo. Compare sempre dentro do setor.",
    relatedMetrics: ["Dívida líquida", "EV/EBITDA", "Fluxo de caixa", "ROIC"],
    rankingLinks: [{ label: "Ações com maior valor de mercado", href: "/rankings/maiores-valor-de-mercado" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Dívida líquida/EBITDA alta é perigosa?", answer: "Pode ser. O risco aumenta quando a dívida é alta e o caixa operacional é instável." },
      { question: "Dívida líquida negativa é boa?", answer: "Pode indicar caixa maior que dívida, mas também deve ser analisado junto com rentabilidade e uso do capital." },
    ],
  },
  {
    slug: "vpa",
    term: "VPA",
    name: "Valor Patrimonial por Ação",
    seoTitle: "O que é VPA? Entenda o Valor Patrimonial por Ação",
    seoDescription: "Saiba o que significa VPA e como ele se relaciona com patrimônio líquido e número de ações.",
    explanation: "O VPA representa o patrimônio líquido dividido pelo número de ações da empresa.",
    formula: "VPA = Patrimônio líquido ÷ Número de ações",
    example: "Se a empresa tem R$ 1 bilhão de patrimônio líquido e 100 milhões de ações, o VPA é R$ 10.",
    interpretation: "O VPA serve de base para o P/VP e ajuda a entender a relação entre preço e patrimônio contábil.",
    attention: "O VPA é contábil. Ele não necessariamente representa o valor justo da ação ou o valor de venda dos ativos.",
    relatedMetrics: ["P/VP", "Patrimônio líquido", "Valor de mercado"],
    rankingLinks: [{ label: "Ações com menor P/VP", href: "/rankings/menores-pvp" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "VPA é preço justo?", answer: "Não. VPA é uma medida contábil. Preço justo exige análise de lucro, caixa, risco e crescimento." },
      { question: "VPA negativo existe?", answer: "Sim, quando o patrimônio líquido é negativo. É um sinal que exige cautela." },
    ],
  },
  {
    slug: "valor-de-mercado",
    term: "Valor de mercado",
    name: "Market cap",
    seoTitle: "O que é Valor de Mercado? Entenda o market cap",
    seoDescription: "Entenda como o valor de mercado é calculado e como ele difere do valor da firma.",
    explanation: "Valor de mercado é o preço da ação multiplicado pela quantidade de ações da empresa. Ele indica quanto o mercado atribui à companhia naquele momento.",
    formula: "Valor de mercado = Preço da ação × Número de ações",
    example: "Se a empresa tem 1 bilhão de ações e cada ação vale R$ 20, o valor de mercado é R$ 20 bilhões.",
    interpretation: "Empresas maiores costumam ter mais liquidez e cobertura, mas valor de mercado alto não significa necessariamente preço atrativo.",
    attention: "Valor de mercado não é a mesma coisa que valor da firma. O valor da firma também considera dívida líquida.",
    relatedMetrics: ["EV/EBITDA", "Dívida líquida", "Volume negociado", "Liquidez diária"],
    rankingLinks: [{ label: "Ações com maior valor de mercado", href: "/rankings/maiores-valor-de-mercado" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Valor de mercado alto significa empresa melhor?", answer: "Não. Significa empresa maior na bolsa, mas qualidade depende de lucro, caixa, governança, dívida e preço." },
      { question: "Market cap muda todo dia?", answer: "Sim. Ele varia conforme o preço da ação e a quantidade de ações em circulação." },
    ],
  },
  {
    slug: "lpa",
    term: "LPA",
    name: "Lucro por Ação",
    seoTitle: "O que é LPA? Entenda o Lucro por Ação",
    seoDescription: "Entenda o lucro por ação, como calcular e como ele se relaciona com P/L e dividendos.",
    explanation: "LPA mostra quanto do lucro líquido corresponde a cada ação da empresa.",
    formula: "LPA = Lucro líquido ÷ Número de ações",
    example: "Se a empresa lucrou R$ 500 milhões e possui 250 milhões de ações, o LPA é R$ 2.",
    interpretation: "LPA crescente pode indicar melhora operacional, mas é preciso avaliar se o lucro é recorrente e se houve recompra ou emissão de ações.",
    attention: "Lucros extraordinários podem inflar o LPA e distorcer o P/L.",
    relatedMetrics: ["P/L", "Payout", "Dividend Yield", "Lucro líquido"],
    rankingLinks: [{ label: "Ações com menor P/L", href: "/rankings/menores-pl" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "LPA alto é sempre melhor?", answer: "Não sozinho. É preciso ver qualidade do lucro, crescimento, dívida e preço da ação." },
      { question: "LPA entra no cálculo do P/L?", answer: "Sim. O P/L é calculado dividindo o preço da ação pelo lucro por ação." },
    ],
  },
  {
    slug: "payout",
    term: "Payout",
    name: "Percentual do lucro distribuído",
    seoTitle: "O que é Payout? Entenda a distribuição de lucro",
    seoDescription: "Veja como o payout mostra a parcela do lucro distribuída em dividendos e JCP.",
    explanation: "Payout indica qual percentual do lucro foi distribuído aos acionistas em dividendos e juros sobre capital próprio.",
    formula: "Payout = Proventos distribuídos ÷ Lucro líquido × 100",
    example: "Se a empresa lucrou R$ 100 milhões e distribuiu R$ 40 milhões, o payout é 40%.",
    interpretation: "Payout alto pode agradar quem busca renda, mas pode reduzir a capacidade de reinvestimento se for elevado demais.",
    attention: "Payout acima de 100% pode indicar distribuição extraordinária ou lucro contábil menor que o caixa distribuído.",
    relatedMetrics: ["Dividend Yield", "LPA", "Fluxo de caixa", "Provento extraordinário"],
    rankingLinks: dividendRankingLinks,
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Payout alto é bom?", answer: "Depende. Pode ser bom para renda, mas também pode limitar crescimento ou indicar evento não recorrente." },
      { question: "Payout e Dividend Yield são iguais?", answer: "Não. Payout compara proventos com lucro. Dividend Yield compara proventos com preço." },
    ],
  },
  {
    slug: "divida-liquida",
    term: "Dívida líquida",
    name: "Dívida descontada do caixa",
    seoTitle: "O que é Dívida Líquida?",
    seoDescription: "Entenda o que é dívida líquida e por que ela importa na análise de empresas.",
    explanation: "Dívida líquida é a dívida bruta da empresa menos o caixa e equivalentes de caixa.",
    formula: "Dívida líquida = Dívida bruta − Caixa e equivalentes",
    example: "Se uma empresa tem R$ 10 bilhões de dívida e R$ 3 bilhões em caixa, a dívida líquida é R$ 7 bilhões.",
    interpretation: "Dívida líquida ajuda a medir risco financeiro e é usada no EV/EBITDA e na dívida líquida/EBITDA.",
    attention: "Dívida precisa ser comparada com geração de caixa, vencimentos, juros e estabilidade da receita.",
    relatedMetrics: ["Dívida líquida/EBITDA", "EV/EBITDA", "Fluxo de caixa", "ROIC"],
    rankingLinks: [{ label: "Ações com maior valor de mercado", href: "/rankings/maiores-valor-de-mercado" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Dívida líquida negativa é possível?", answer: "Sim. Isso ocorre quando o caixa supera a dívida bruta." },
      { question: "Toda dívida é ruim?", answer: "Não. Dívida pode financiar crescimento, mas precisa ser sustentável." },
    ],
  },
  {
    slug: "valor-patrimonial-por-cota",
    term: "VP/Cota",
    name: "Valor patrimonial por cota",
    seoTitle: "O que é VP/Cota em FIIs?",
    seoDescription: "Entenda o valor patrimonial por cota em fundos imobiliários e sua relação com P/VP.",
    explanation: "VP/Cota indica o patrimônio líquido do fundo dividido pelo número de cotas. É uma referência contábil usada para calcular P/VP.",
    formula: "VP/Cota = Patrimônio líquido do FII ÷ Número de cotas",
    example: "Se o FII tem R$ 1 bilhão de patrimônio e 10 milhões de cotas, o VP/Cota é R$ 100.",
    interpretation: "Ao comparar o preço da cota com o VP/Cota, o investidor encontra o P/VP do fundo.",
    attention: "O VP/Cota depende da marcação dos imóveis e ativos do fundo. Ele não garante preço justo nem liquidez de venda.",
    relatedMetrics: ["P/VP", "Patrimônio líquido", "Vacância", "Dividend Yield"],
    rankingLinks: [{ label: "FIIs com menor P/VP", href: "/rankings/fiis-menor-pvp" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "VP/Cota é valor justo?", answer: "Não. É uma referência patrimonial, mas preço justo depende de qualidade, renda, risco e mercado." },
      { question: "VP/Cota muda?", answer: "Sim. Ele muda com reavaliação de ativos, emissão de cotas, amortizações e resultado do fundo." },
    ],
  },
  {
    slug: "patrimonio-liquido",
    term: "Patrimônio líquido",
    name: "Capital próprio contábil",
    seoTitle: "O que é Patrimônio Líquido?",
    seoDescription: "Entenda o patrimônio líquido em empresas e fundos imobiliários.",
    explanation: "Patrimônio líquido representa a diferença entre ativos e passivos. Em empresas, é o capital dos acionistas. Em FIIs, representa o patrimônio do fundo.",
    formula: "Patrimônio líquido = Ativos − Passivos",
    example: "Se uma empresa tem R$ 10 bilhões em ativos e R$ 6 bilhões em passivos, o patrimônio líquido é R$ 4 bilhões.",
    interpretation: "Serve de base para indicadores como ROE, VPA, VP/Cota e P/VP.",
    attention: "Patrimônio líquido é contábil. Pode não refletir o valor econômico real dos ativos.",
    relatedMetrics: ["ROE", "VPA", "P/VP", "Valor patrimonial por cota"],
    rankingLinks: [{ label: "FIIs com maior patrimônio", href: "/rankings/fiis-maior-patrimonio" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Patrimônio líquido negativo é ruim?", answer: "Geralmente exige muita cautela, pois indica passivos superiores aos ativos." },
      { question: "Patrimônio líquido é caixa?", answer: "Não. Ele inclui ativos e passivos contábeis, não apenas dinheiro disponível." },
    ],
  },
  {
    slug: "liquidez-diaria",
    term: "Liquidez diária",
    name: "Facilidade de negociação",
    seoTitle: "O que é Liquidez Diária na bolsa?",
    seoDescription: "Entenda liquidez diária, volume financeiro e por que isso importa em ações e FIIs.",
    explanation: "Liquidez diária indica a facilidade de comprar ou vender um ativo no mercado sem distorcer muito o preço.",
    formula: "Liquidez diária pode ser estimada pelo volume financeiro médio negociado por dia",
    example: "Um ativo que negocia R$ 100 milhões por dia tende a ter mais liquidez que outro que negocia R$ 100 mil por dia.",
    interpretation: "Mais liquidez reduz risco de dificuldade para entrar ou sair de uma posição, especialmente em valores maiores.",
    attention: "Baixa liquidez pode causar spreads maiores, oscilações bruscas e preços menos representativos.",
    relatedMetrics: ["Volume negociado", "Valor de mercado", "Volatilidade"],
    rankingLinks: [
      { label: "Ações mais negociadas", href: "/rankings/acoes-mais-negociadas" },
      { label: "FIIs mais negociados", href: "/rankings/fiis-mais-negociados" },
    ],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Liquidez alta é sempre melhor?", answer: "Ela ajuda na negociação, mas não significa que o ativo seja bom investimento." },
      { question: "Volume e liquidez são a mesma coisa?", answer: "Volume é uma medida usada para observar liquidez, mas liquidez também envolve spread e profundidade do mercado." },
    ],
  },
  {
    slug: "volume-negociado",
    term: "Volume negociado",
    name: "Quantidade financeira negociada",
    seoTitle: "O que é Volume Negociado?",
    seoDescription: "Entenda o volume negociado e como ele ajuda a avaliar liquidez de ações e FIIs.",
    explanation: "Volume negociado mostra quanto dinheiro ou quantas unidades foram negociadas em um período.",
    formula: "Volume financeiro = Quantidade negociada × Preço médio",
    example: "Se 1 milhão de ações foram negociadas a R$ 20, o volume financeiro aproximado é R$ 20 milhões.",
    interpretation: "Volume maior costuma indicar mercado mais ativo e maior facilidade de negociação.",
    attention: "Picos de volume podem ocorrer por notícias, rebalanceamentos ou eventos específicos e não se repetir.",
    relatedMetrics: ["Liquidez diária", "Valor de mercado", "Preço"],
    rankingLinks: [
      { label: "Ações mais negociadas", href: "/rankings/acoes-mais-negociadas" },
      { label: "FIIs mais negociados", href: "/rankings/fiis-mais-negociados" },
    ],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Volume alto indica compra?", answer: "Não necessariamente. Todo negócio tem comprador e vendedor. Volume alto indica atividade, não direção por si só." },
      { question: "Volume baixo é problema?", answer: "Pode ser, porque dificulta negociação e pode aumentar a diferença entre compra e venda." },
    ],
  },
  {
    slug: "vacancia",
    term: "Vacância",
    name: "Espaço vago em imóveis de FIIs",
    seoTitle: "O que é Vacância em FIIs?",
    seoDescription: "Entenda vacância física e financeira em fundos imobiliários.",
    explanation: "Vacância mede a parcela dos imóveis do fundo que está vaga ou sem gerar receita contratada.",
    formula: "Vacância física = Área vaga ÷ Área total. Vacância financeira = Receita potencial vaga ÷ Receita potencial total.",
    example: "Se um prédio tem 10.000 m² e 1.000 m² estão vazios, a vacância física é 10%.",
    interpretation: "Vacância menor tende a indicar ocupação melhor, mas precisa ser analisada junto com qualidade dos contratos e perfil dos inquilinos.",
    attention: "Vacância zero não elimina riscos. Contratos podem vencer, inquilinos podem sair e receitas podem ser renegociadas.",
    relatedMetrics: ["Dividend Yield", "P/VP", "Segmento de FII", "Patrimônio líquido"],
    rankingLinks: [{ label: "FIIs com maior Dividend Yield", href: "/rankings/fiis-maior-dividend-yield" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Vacância alta é sempre ruim?", answer: "Geralmente aumenta risco, mas pode haver plano de ocupação ou imóveis em transição." },
      { question: "Vacância física e financeira são iguais?", answer: "Não. A física mede área vaga. A financeira mede impacto potencial em receita." },
    ],
  },
  {
    slug: "segmento-de-fii",
    term: "Segmento de FII",
    name: "Tipo de fundo imobiliário",
    seoTitle: "O que é Segmento de FII?",
    seoDescription: "Conheça os principais segmentos de fundos imobiliários e como comparar FIIs.",
    explanation: "Segmento de FII identifica o tipo de ativo ou estratégia do fundo, como logística, shopping, papel, lajes corporativas, híbrido ou renda urbana.",
    formula: "Não há fórmula. É uma classificação da estratégia e dos ativos do fundo.",
    example: "Um FII de logística investe em galpões. Um FII de papel investe em CRIs. Um FII de shopping investe em participações em shoppings.",
    interpretation: "Comparações são mais justas dentro do mesmo segmento, porque riscos, vacância, indexadores e contratos mudam bastante.",
    attention: "FIIs de segmentos diferentes podem ter DY, P/VP e riscos muito diferentes. Evite comparar apenas pelo maior rendimento.",
    relatedMetrics: ["Dividend Yield", "P/VP", "Vacância", "Liquidez diária"],
    rankingLinks: [
      { label: "FIIs com maior Dividend Yield", href: "/rankings/fiis-maior-dividend-yield" },
      { label: "FIIs com menor P/VP", href: "/rankings/fiis-menor-pvp" },
    ],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Qual segmento de FII é melhor?", answer: "Não existe melhor universal. Cada segmento tem riscos, ciclos e fontes de receita diferentes." },
      { question: "FII de papel é igual a FII de tijolo?", answer: "Não. FIIs de papel investem principalmente em recebíveis. FIIs de tijolo investem em imóveis físicos." },
    ],
  },
  {
    slug: "ifix",
    term: "IFIX",
    name: "Índice de Fundos Imobiliários",
    seoTitle: "O que é IFIX? Entenda o índice de FIIs",
    seoDescription: "Entenda o IFIX, índice que acompanha uma carteira teórica de fundos imobiliários listados na bolsa.",
    explanation: "O IFIX é um índice que mede o desempenho médio de uma carteira teórica de fundos imobiliários negociados na bolsa brasileira.",
    formula: "Não é fórmula de indicador. É um índice calculado pela bolsa a partir de critérios próprios de composição e ponderação.",
    example: "Quando o IFIX sobe, significa que a carteira teórica de FIIs teve valorização média positiva no período, considerando a metodologia do índice.",
    interpretation: "Serve como referência de mercado para comparar desempenho de FIIs ou carteiras de FIIs.",
    attention: "Um FII pode subir enquanto o IFIX cai, e o contrário também. O índice é referência, não garantia de comportamento individual.",
    relatedMetrics: ["Dividend Yield", "P/VP", "Volume negociado", "Liquidez diária"],
    rankingLinks: [{ label: "Rankings de FIIs", href: "/rankings" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "IFIX é uma recomendação?", answer: "Não. É um índice de referência do mercado de FIIs." },
      { question: "Todo FII entra no IFIX?", answer: "Não. A composição depende dos critérios da bolsa." },
    ],
  },
  {
    slug: "ibovespa",
    term: "Ibovespa",
    name: "Principal índice da bolsa brasileira",
    seoTitle: "O que é Ibovespa?",
    seoDescription: "Entenda o Ibovespa, principal índice de ações da B3.",
    explanation: "O Ibovespa é o principal índice de ações da bolsa brasileira e acompanha uma carteira teórica de empresas com alta negociabilidade.",
    formula: "Não é fórmula de indicador. É um índice calculado pela bolsa conforme metodologia própria.",
    example: "Quando o Ibovespa sobe 1%, a carteira teórica do índice teve valorização média próxima disso no período.",
    interpretation: "Serve como referência para o mercado acionário brasileiro e para comparação com carteiras e fundos.",
    attention: "O Ibovespa é concentrado em empresas grandes e líquidas. Ele não representa todas as ações da bolsa igualmente.",
    relatedMetrics: ["Valor de mercado", "Volume negociado", "Liquidez diária"],
    rankingLinks: [{ label: "Ações mais negociadas", href: "/rankings/acoes-mais-negociadas" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Ibovespa representa toda a bolsa?", answer: "Não. Ele representa uma carteira teórica de ações selecionadas por critérios de liquidez e participação." },
      { question: "Uma ação fora do Ibovespa é ruim?", answer: "Não necessariamente. Pode ser menor ou menos líquida, mas ainda assim ter fundamentos relevantes." },
    ],
  },
  {
    slug: "cagr",
    term: "CAGR",
    name: "Taxa composta de crescimento anual",
    seoTitle: "O que é CAGR?",
    seoDescription: "Entenda o CAGR, taxa composta usada para medir crescimento anual médio.",
    explanation: "CAGR mostra a taxa anual composta necessária para transformar um valor inicial em um valor final ao longo de um período.",
    formula: "CAGR = (Valor final ÷ Valor inicial)^(1/n) − 1",
    example: "Se a receita saiu de R$ 100 milhões para R$ 161 milhões em 5 anos, o CAGR é aproximadamente 10% ao ano.",
    interpretation: "Ajuda a comparar crescimento de receita, lucro, patrimônio ou dividendos em períodos diferentes.",
    attention: "CAGR suaviza o caminho. Ele não mostra oscilações, quedas ou anos ruins dentro do período.",
    relatedMetrics: ["Receita", "Lucro líquido", "Dividend Yield", "ROE"],
    rankingLinks: [{ label: "Rankings de ações", href: "/rankings" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "CAGR é média simples?", answer: "Não. É uma taxa composta, por isso considera crescimento acumulado no tempo." },
      { question: "CAGR alto garante futuro bom?", answer: "Não. Ele mostra passado, não garante crescimento futuro." },
    ],
  },
  {
    slug: "provento-extraordinario",
    term: "Provento extraordinário",
    name: "Pagamento não recorrente",
    seoTitle: "O que é Provento Extraordinário?",
    seoDescription: "Entenda proventos extraordinários e por que eles podem distorcer o Dividend Yield.",
    explanation: "Provento extraordinário é um pagamento fora do padrão recorrente, muitas vezes ligado a venda de ativo, evento societário, lucro não recorrente ou distribuição excepcional.",
    formula: "Não há fórmula única. O ponto central é identificar se o pagamento não representa a renda recorrente do ativo.",
    example: "Um FII pode vender um imóvel e distribuir ganho extraordinário. Isso pode elevar o DY de 12 meses, mas não significa que o pagamento se repetirá.",
    interpretation: "Deve ser separado da renda recorrente para evitar leitura exagerada de dividendos ou rendimentos.",
    attention: "Rankings de maior DY podem ficar enganosos se tratarem proventos extraordinários como renda normal.",
    relatedMetrics: ["Dividend Yield", "Payout", "Amortização", "Fluxo de caixa"],
    rankingLinks: dividendRankingLinks,
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Provento extraordinário entra no DY?", answer: "Pode entrar em alguns cálculos, dependendo da metodologia. Por isso é importante verificar a recorrência." },
      { question: "Provento extraordinário é ruim?", answer: "Não necessariamente. O problema é tratá-lo como se fosse recorrente." },
    ],
  },
  {
    slug: "amortizacao",
    term: "Amortização",
    name: "Devolução consulta inicial de capital",
    seoTitle: "O que é Amortização em FIIs e ativos?",
    seoDescription: "Entenda amortização e por que ela pode distorcer a leitura de rendimentos.",
    explanation: "Amortização é uma devolução consulta inicial de capital ao cotista ou investidor. Em FIIs, pode ocorrer em eventos de venda de ativos, encerramento ou reestruturação.",
    formula: "Não é indicador operacional. É um evento financeiro de devolução de capital.",
    example: "Se um FII amortiza R$ 10 por cota, o cotista recebe esse valor, mas isso pode reduzir patrimônio ou refletir desinvestimento.",
    interpretation: "Amortização não deve ser confundida com renda recorrente. Pode elevar o valor recebido no período sem indicar geração mensal sustentável.",
    attention: "Ao analisar DY, é importante entender se o pagamento veio de rendimento recorrente ou amortização.",
    relatedMetrics: ["Dividend Yield", "Provento extraordinário", "Patrimônio líquido", "VP/Cota"],
    rankingLinks: [{ label: "FIIs com maior Dividend Yield", href: "/rankings/fiis-maior-dividend-yield" }],
    assetLinks: defaultAssetLinks,
    faq: [
      { question: "Amortização é dividendo?", answer: "Não exatamente. Ela costuma ser devolução de capital, não renda operacional recorrente." },
      { question: "Amortização pode distorcer DY?", answer: "Sim. Se incluída sem tratamento, pode fazer o DY parecer artificialmente alto." },
    ],
  },
];

export function getGlossaryItem(slug: string): GlossaryItem | undefined {
  return glossaryItems.find((item) => item.slug === slug);
}
