export const popularStocks = [
  "PETR4",
  "VALE3",
  "ITUB4",
  "BBDC4",
  "BBAS3",
  "ABEV3",
  "B3SA3",
  "WEGE3",
  "MGLU3",
  "PETR3",
  "ITSA4",
  "RENT3",
  "LREN3",
  "PRIO3",
  "SUZB3",
  "GGBR4",
  "HAPV3",
  "RADL3",
  "AXIA3",
  "RAIL3",
  "CMIG4",
  "CPLE6",
  "TOTS3",
  "VBBR3",
  "BBSE3",
  "BPAC11",
  "EQTL3",
  "CSNA3",
  "BBDC3",
  "ITUB3",
  "USIM5",
  "COGN3",
  "AZUL4",
  "MBRF3",
  "MRVE3",
  "CYRE3",
  "NATU3",
  "EMBJ3",
  "KLBN11"
];

export const popularFIIs = [
  "MXRF11",
  "KNCR11",
  "CPTS11",
  "HGLG11",
  "XPML11",
  "VISC11",
  "KNSC11",
  "RBRR11",
  "HGRU11",
  "BTLG11",
  "XPLG11",
  "KNRI11",
  "IRDM11",
  "VGIR11",
  "RZTR11",
  "TRXF11",
  "HSML11",
  "MALL11",
  "BCFF11",
  "RBRF11",
  "PVBI11",
  "BRCO11",
  "HGCR11",
  "RECR11",
  "KNIP11",
  "KNHY11",
  "VILG11",
  "RBRL11",
  "GGRC11",
  "LVBI11"
];

export type StockSearchFallback = {
  symbol: string;
  name: string;
  sector?: string;
};

export const stockSuggestionsFallback: StockSearchFallback[] = [
  { symbol: "PETR4", name: "Petrobras PN", sector: "Petróleo e Gás" },
  { symbol: "PETR3", name: "Petrobras ON", sector: "Petróleo e Gás" },
  { symbol: "VALE3", name: "Vale ON", sector: "Mineração" },
  { symbol: "ITUB4", name: "Itaú Unibanco PN", sector: "Bancos" },
  { symbol: "ITUB3", name: "Itaú Unibanco ON", sector: "Bancos" },
  { symbol: "BBAS3", name: "Banco do Brasil ON", sector: "Bancos" },
  { symbol: "BBDC4", name: "Bradesco PN", sector: "Bancos" },
  { symbol: "BBDC3", name: "Bradesco ON", sector: "Bancos" },
  { symbol: "BBSE3", name: "BB Seguridade ON", sector: "Seguradoras" },
  { symbol: "WEGE3", name: "WEG ON", sector: "Máquinas e Equipamentos" },
  { symbol: "ABEV3", name: "Ambev ON", sector: "Bebidas" },
  { symbol: "TAEE11", name: "Taesa Unit", sector: "Energia Elétrica" },
  { symbol: "EGIE3", name: "Engie Brasil ON", sector: "Energia Elétrica" },
  { symbol: "CSMG3", name: "Copasa ON", sector: "Saneamento" },
  { symbol: "RANI3", name: "Irani ON", sector: "Papel e Embalagens" },
  { symbol: "CMIG4", name: "Cemig PN", sector: "Energia Elétrica" },
  { symbol: "CPLE6", name: "Copel PNB", sector: "Energia Elétrica" },
  { symbol: "KLBN11", name: "Klabin Unit", sector: "Papel e Celulose" },
  { symbol: "SUZB3", name: "Suzano ON", sector: "Papel e Celulose" },
  { symbol: "RENT3", name: "Localiza ON", sector: "Aluguel de veículos" },
  { symbol: "MGLU3", name: "Magazine Luiza ON", sector: "Varejo" },
  { symbol: "LREN3", name: "Lojas Renner ON", sector: "Varejo" },
  { symbol: "RAIL3", name: "Rumo ON", sector: "Transporte" },
  { symbol: "B3SA3", name: "B3 ON", sector: "Serviços Financeiros" },
  { symbol: "PRIO3", name: "PRIO ON", sector: "Petróleo e Gás" },
  { symbol: "GGBR4", name: "Gerdau PN", sector: "Siderurgia" },
  { symbol: "HAPV3", name: "Hapvida ON", sector: "Saúde" },
  { symbol: "RADL3", name: "Raia Drogasil ON", sector: "Varejo farmacêutico" },
  { symbol: "AXIA3", name: "Eletrobras ON", sector: "Energia Elétrica" },
  { symbol: "TOTS3", name: "Totvs ON", sector: "Tecnologia" },
  { symbol: "VBBR3", name: "Vibra Energia ON", sector: "Distribuição de combustíveis" },
  { symbol: "BPAC11", name: "BTG Pactual Unit", sector: "Bancos" },
  { symbol: "EQTL3", name: "Equatorial ON", sector: "Energia Elétrica" },
  { symbol: "CSNA3", name: "CSN ON", sector: "Siderurgia" },
  { symbol: "USIM5", name: "Usiminas PNA", sector: "Siderurgia" },
  { symbol: "COGN3", name: "Cogna ON", sector: "Educação" },
  { symbol: "AZUL4", name: "Azul PN", sector: "Transporte aéreo" },
  { symbol: "MBRF3", name: "BRF ON", sector: "Alimentos" },
  { symbol: "MRVE3", name: "MRV ON", sector: "Construção" },
  { symbol: "CYRE3", name: "Cyrela ON", sector: "Construção" },
  { symbol: "NATU3", name: "Natura ON", sector: "Consumo" },
  { symbol: "EMBJ3", name: "Embraer ON", sector: "Aeronáutico" },
  { symbol: "WIZC3", name: "Wiz Co ON", sector: "Corretoras de seguros" },

  { symbol: "NTCO3", name: "Natura ON (antigo, atual NATU3)", sector: "Consumo" },
  { symbol: "EMBR3", name: "Embraer ON (antigo, atual EMBJ3)", sector: "Aeronáutico" },
  { symbol: "ELET3", name: "Eletrobras ON (antigo, atual AXIA3)", sector: "Energia Elétrica" },
  { symbol: "BRFS3", name: "BRF ON (antigo, atual MBRF3)", sector: "Alimentos" },
  { symbol: "JBSS3", name: "JBS ON (antigo, atual BDR JBSS32)", sector: "Alimentos" },
  { symbol: "MXRF11", name: "Maxi Renda FII", sector: "FII" },
  { symbol: "KNCR11", name: "Kinea Rendimentos Imobiliários FII", sector: "FII" },
  { symbol: "CPTS11", name: "Capitânia Securities II FII", sector: "FII" },
  { symbol: "HGLG11", name: "CSHG Logística FII", sector: "FII" },
  { symbol: "XPML11", name: "XP Malls FII", sector: "FII" },
  { symbol: "VISC11", name: "Vinci Shopping Centers FII", sector: "FII" },
  { symbol: "KNSC11", name: "Kinea Securities FII", sector: "FII" },
  { symbol: "RBRR11", name: "RBR Rendimentos High Grade FII", sector: "FII" },
  { symbol: "HGRU11", name: "CSHG Renda Urbana FII", sector: "FII" },
  { symbol: "BTLG11", name: "BTG Pactual Logística FII", sector: "FII" },
  { symbol: "XPLG11", name: "XP Log FII", sector: "FII" },
  { symbol: "KNRI11", name: "Kinea Renda Imobiliária FII", sector: "FII" },
  { symbol: "IRDM11", name: "Iridium Recebíveis Imobiliários FII", sector: "FII" },
  { symbol: "VGIR11", name: "Valora RE III FII", sector: "FII" },
  { symbol: "RZTR11", name: "Riza Terrax FII", sector: "FII" },
  { symbol: "TRXF11", name: "TRX Real Estate FII", sector: "FII" },
  { symbol: "HSML11", name: "HSI Malls FII", sector: "FII" },
  { symbol: "MALL11", name: "Malls Brasil Plural FII", sector: "FII" },
  { symbol: "BCFF11", name: "BTG Pactual Fundo de Fundos FII", sector: "FII" },
  { symbol: "RBRF11", name: "RBR Alpha Multiestratégia FII", sector: "FII" },
  { symbol: "PVBI11", name: "VBI Prime Properties FII", sector: "FII" },
  { symbol: "BRCO11", name: "Bresco Logística FII", sector: "FII" },
  { symbol: "HGCR11", name: "CSHG Recebíveis Imobiliários FII", sector: "FII" },
  { symbol: "RECR11", name: "REC Recebíveis Imobiliários FII", sector: "FII" },
  { symbol: "KNIP11", name: "Kinea Índices de Preços FII", sector: "FII" },
  { symbol: "KNHY11", name: "Kinea High Yield CRI FII", sector: "FII" },
  { symbol: "VILG11", name: "Vinci Logística FII", sector: "FII" },
  { symbol: "RBRL11", name: "RBR Log FII", sector: "FII" },
  { symbol: "GGRC11", name: "GGR Covepi Renda FII", sector: "FII" },
  { symbol: "LVBI11", name: "VBI Logístico FII", sector: "FII" }
];

export const rankingStocks = [
  "PETR4", "PETR3", "VALE3", "ITUB4", "ITUB3", "BBAS3", "BBDC4", "BBDC3",
  "BBSE3", "WEGE3", "ABEV3", "TAEE11", "EGIE3", "CSMG3", "RANI3", "CMIG4",
  "CPLE6", "KLBN11", "SUZB3", "RENT3", "MGLU3", "LREN3", "RAIL3", "B3SA3",
  "ALPA4", "ASAI3", "AURE3", "AZUL4", "BEEF3", "BPAC11", "BRAP4", "MBRF3",
  "BRKM5", "BRSR6", "CCRO3", "CMIG3", "CMIN3", "COGN3", "CPFE3", "CPLE3",
  "CSAN3", "CSNA3", "CURY3", "CYRE3", "DIRR3", "DXCO3", "ECOR3", "AXIA3",
  "AXIA6", "EMBJ3", "ENEV3", "ENGI11", "EQTL3", "EVEN3", "EZTC3", "FLRY3",
  "GGBR4", "GOAU4", "HAPV3", "HYPE3", "IRBR3", "ITSA3", "ITSA4",
  "LEVE3", "MDIA3", "MILS3", "MOVI3", "MBRF3", "MRVE3", "MULT3", "NEOE3",
  "NATU3", "ODPV3", "PCAR3", "POMO4", "PRIO3", "PSSA3", "RADL3", "RAIZ4",
  "RDOR3", "ROMI3", "SANB11", "SAPR11", "SBSP3", "SLCE3", "SMTO3", "STBP3",
  "TIMS3", "TOTS3", "TRPL4", "UGPA3", "USIM5", "VBBR3", "VIVT3", "VLID3",
  "WIZC3", "YDUQ3"
];

export const rankingFIIs = [
  "MXRF11", "KNCR11", "CPTS11", "HGLG11", "XPML11", "VISC11", "KNSC11", "RBRR11",
  "HGRU11", "BTLG11", "XPLG11", "KNRI11", "IRDM11", "VGIR11", "RZTR11", "TRXF11",
  "HSML11", "MALL11", "BCFF11", "RBRF11", "PVBI11", "BRCO11", "HGCR11", "RECR11",
  "KNIP11", "KNHY11", "VILG11", "RBRL11", "GGRC11", "LVBI11", "ALZR11", "BCRI11",
  "BRCR11", "DEVA11", "HCTR11", "HGPO11", "HGRE11", "HSLG11", "JSRE11", "KFOF11",
  "KNCA11", "MCCI11", "OUJP11", "RBRP11", "RBVA11", "RECT11", "TEPP11", "URPR11",
  "VINO11", "VRTA11", "XPIN11", "XPPR11"
];
